### ISSUE TITLE
Compilation error on Due with latest Arduino IDE version 2

### ISSUE THREAD

**Issue by mohimoti** [drhaney/pt100rtd#10]
I tried to compile the example code on Arduino but it gives below error message:
In file included from C:\Users\mohi\Documents\Arduino\libraries\pt100rtd-master\examples\pt100_temperature\pt100_temperature.ino:24:0:
C:\Users\mohi\Documents\Arduino\libraries\pt100rtd-master/pt100rtd.h:30:22: fatal error: pgmspace.h: No such file or directory
 #include <pgmspace.h>
                      ^
compilation terminated.

exit status 1

Compilation error: exit status 1

it works with Adafruit example on Max31865

**Comment by drhaney** [comment]
If you have a 32-bit ARM controller such as the DUE, **_you don't need the pt100 library_**.  Use the Callendar-Van Dusen computation as presented in the Adafruit_MAX31865 library.

This library was written because floating point computations are costly for for 8-bit AVR  MCUs having limited processing and memory resources, namely Arduino 2009, UNO, and similar.
