### ISSUE TITLE
PlatformIO library registry has wrong version - 0.1

### ISSUE THREAD

**Issue by imsunburnt** [drhaney/pt100rtd#11]
PlatformIO library registry does not get the latest version of the code.  It gets version 0.1 but the latest version on Github has different code, namely pt100rtd.h has 
`
#if (defined(__AVR__))
#include <avr\pgmspace.h>
#else
#include <pgmspace.h>
#endif
`
and version 0.1 has
`
#include <avr\pgmspace.h>
`

Version 0.1 will not compile with the latest release of Espressif 32.

I do not know how to file an issue for PlatformIO Library Registry, I thought the author of this repository could cause an update to the registry to happen.

**Comment by drhaney** [comment]
You wrote:
>>Version 0.1 will not compile with the latest release of Espressif 32.

RTFM.
In the README.md file, I wrote:

> **WHY NOT**
> **If you have a 32-bit ARM MCU, then you don't need this!**
> It is intended for 8-bit MCUs lacking SRAM and speed, namely the one used in the Arduino UNO and similar.
> 

Since you are compiling for a 32 bit MPU, use the Callendar-Van Dusen equation, the AN709 polynomial, or the rational 
polynomial fraction for calculating the temperature.   They are finished old science and do not require attribution.
 
 You can copy them directly from the **_pt100rtd.cpp_** file starting at **_line 232_**. 
 
 Any one of them is small enough to be included directly in your code and would not require the header file.
